info:
  contact: {}
paths:
  /api/heartbeat:
    get:
      responses:
        "204":
          description: ""
        "400":
          description: ""
      summary: Heartbeat metric
      tags:
      - metrics
swagger: "2.0"
